version: "3.7"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - --api.insecure=true
      - --api=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.vite.address=:5173
      - --entrypoints.db.address=:3306
      - --api.dashboard=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=false
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "5173:5173"
      - "8000:8000"
      - "6379:6379"
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`${DOMAIN}`, `traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=false
      - traefik.http.routers.traefik.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD_HASH}
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - traefik.enable=true
      - traefik.http.routers.https.rule=Host(`whoami.${DOMAIN}`)
      - traefik.http.routers.https.entrypoints=http
      - traefik.http.routers.https.tls=false
      - traefik.http.routers.https.tls.certresolver=${CERT_RESOLVER}
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: host
